import {
  ShieldCheck,
  KeyRound,
  Split,
  Link2,
  Landmark,
  Smartphone,
  LayoutGrid,
  Wallet,
  CircleDollarSign,
  ArrowLeftRight,
  Building2,
  RefreshCw,
  Rocket,
  Layers,
  LineChart,
  Wrench,
  Gauge,
  Newspaper,
  Calendar,
  Video,
  Trophy,
  FileText,
  Mic,
  Sparkles,
  ChevronDown,
  ChevronRight,
  ArrowRight,
  Check,
  CheckCircle2,
  Globe,
  Lock,
  Network,
  ListChecks,
  Cpu,
  ShieldAlert,
  Fingerprint,
  Boxes,
  Puzzle,
  BookOpen,
  Users,
  Zap,
  CircleHelp,
  Download,
  Play,
  Circle,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "shield-check": ShieldCheck,
  "key-round": KeyRound,
  split: Split,
  "link-2": Link2,
  landmark: Landmark,
  smartphone: Smartphone,
  "layout-grid": LayoutGrid,
  wallet: Wallet,
  "circle-dollar-sign": CircleDollarSign,
  "arrow-left-right": ArrowLeftRight,
  "building-2": Building2,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  layers: Layers,
  "line-chart": LineChart,
  wrench: Wrench,
  gauge: Gauge,
  newspaper: Newspaper,
  calendar: Calendar,
  video: Video,
  trophy: Trophy,
  "file-text": FileText,
  mic: Mic,
  sparkles: Sparkles,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "arrow-right": ArrowRight,
  check: Check,
  "check-circle": CheckCircle2,
  globe: Globe,
  lock: Lock,
  network: Network,
  "list-checks": ListChecks,
  cpu: Cpu,
  "shield-alert": ShieldAlert,
  fingerprint: Fingerprint,
  boxes: Boxes,
  puzzle: Puzzle,
  "book-open": BookOpen,
  users: Users,
  zap: Zap,
  help: CircleHelp,
  download: Download,
  play: Play,
  circle: Circle,
};

export type IconName = keyof typeof ICONS | string;

export function Icon({
  name,
  className,
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
